$onesync: on

name: A-TH
version: 1.0.0
author: A-TH
description: A-TH

tasks:


 - action: download_file
    path: ./tmp/files/ghmattimysql.zip
    url: https://github.com/teerajat1/npcore-server-1/tree/main/server-data/resources
